# Generated by Django 4.1.13 on 2024-08-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=256, unique_for_date='publish'),
        ),
    ]
